
name = "DashObservable"
uuid = "1b08a953-4be3-4667-9a23-593fe9ab3f8d"
authors = ["Thomas Ballinger <thomasballinger@gmail.com>"]
version = "0.0.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3"
